import { Menus } from '@/types/menu';

export const menuData: Menus[] = [
    {
        id: '0',
        title: '系统首页',
        index: '/dashboard',
        icon: 'Odometer',
        permiss: 'menu:dashboard:view',
    },
    {
        id: '1',
        title: '系统管理',
        index: '1',
        icon: 'HomeFilled',
        children: [
            {
                id: 'menu:system:user',
                pid: '1',
                index: '/system-user',
                title: '用户管理',
                permiss: 'menu:system:user',
            },
            {
                id: 'menu:system:role',
                pid: '1',
                index: '/system-role',
                title: '角色管理',
                permiss: 'menu:system:role',
            },
            {
                id: '13',
                pid: '1',
                index: '/system-menu',
                title: '菜单管理',
                permiss: 'menu:system:menu',
            },
        ],
    },
    {
        id: '2',
        title: '组件',
        index: '2-1',
        icon: 'Calendar',
        children: [
            {
                id: '21',
                pid: '3',
                index: '/form',
                title: '表单',
                permiss: 'menu:component:form',
            },
            {
                id: '22',
                pid: '3',
                index: '/upload',
                title: '上传',
                permiss: 'menu:component:upload',
            },
            {
                id: '23',
                pid: '2',
                index: '/carousel',
                title: '走马灯',
                permiss: 'menu:component:carousel',
            },
            {
                id: '24',
                pid: '2',
                index: '/calendar',
                title: '日历',
                permiss: 'menu:component:calendar',
            },
            {
                id: '25',
                pid: '2',
                index: '/watermark',
                title: '水印',
                permiss: 'menu:component:watermark',
            },
            {
                id: '26',
                pid: '2',
                index: '/tour',
                title: '分布引导',
                permiss: 'menu:component:tour',
            },
            {
                id: '27',
                pid: '2',
                index: '/steps',
                title: '步骤条',
                permiss: 'menu:component:steps',
            },
            {
                id: '28',
                pid: '2',
                index: '/statistic',
                title: '统计',
                permiss: 'menu:component:statistic',
            },
            {
                id: '29',
                pid: '3',
                index: '29',
                title: '三级菜单',
                children: [
                    {
                        id: '291',
                        pid: '29',
                        index: '/editor',
                        title: '富文本编辑器',
                        permiss: 'menu:component:editor',
                    },
                    {
                        id: '292',
                        pid: '29',
                        index: '/markdown',
                        title: 'markdown编辑器',
                        permiss: 'menu:component:markdown',
                    },
                ],
            },
        ],
    },
    {
        id: '3',
        title: '表格',
        index: '3',
        icon: 'Calendar',
        children: [
            {
                id: '31',
                pid: '3',
                index: '/table',
                title: '基础表格',
                permiss: 'menu:table:base',
            },
            {
                id: '32',
                pid: '3',
                index: '/table-editor',
                title: '可编辑表格',
                permiss: 'menu:table:editable',
            },
            {
                id: '33',
                pid: '3',
                index: '/import',
                title: '导入Excel',
                permiss: 'menu:table:import',
            },
            {
                id: '34',
                pid: '3',
                index: '/export',
                title: '导出Excel',
                permiss: 'menu:table:export',
            },
        ],
    },
    {
        id: '4',
        icon: 'PieChart',
        index: '4',
        title: '图表',
        children: [
            {
                id: '41',
                pid: '4',
                index: '/schart',
                title: 'schart图表',
                permiss: 'menu:chart:schart',
            },
            {
                id: '42',
                pid: '4',
                index: '/echarts',
                title: 'echarts图表',
                permiss: 'menu:chart:echarts',
            },
        ],
    },
    {
        id: '5',
        icon: 'Guide',
        index: '/icon',
        title: '图标',
        permiss: 'menu:icon:view',
    },
    {
        id: '7',
        icon: 'Brush',
        index: '/theme',
        title: '主题',
        permiss: 'menu:theme:view',
    },
    {
        id: 'community',
        icon: 'OfficeBuilding',
        index: 'community',
        title: '社区管理',
        children: [
            {
                id: 'community-info',
                pid: 'community',
                index: '/community/info',
                title: '社区信息管理',
            },
            {
                id: 'community-rooms',
                pid: 'community',
                index: '/rooms',
                title: '房间列表',
                permiss: 'community:rooms',
            },
            {
                id: 'community-room-bookings',
                pid: 'community',
                index: '/room-bookings',
                title: '房间预订',
                permiss: 'community:room-bookings',
            },
            {
                id: 'community-room-photos',
                pid: 'community',
                index: '/room-photos',
                title: '房间照片',
                permiss: 'community:room-photos',
            },
            {
                id: 'community-room-rate-plans',
                pid: 'community',
                index: '/room-rate-plans',
                title: '房间定价',
                permiss: 'community:room-rate-plans',
            },
        ],
    },
    {
        id: 'activity',
        icon: 'Tickets',
        index: 'activity',
        title: '活动管理',
        children: [
            {
                id: 'activity:list',
                pid: 'activity',
                index: '/activities',
                title: '活动列表',
                permiss: 'community:activities',
            },
        ],
    },
    {
        id: 'jobs',
        icon: 'Briefcase',
        index: 'jobs',
        title: '工作机会',
        children: [
            {
                id: 'jobs:list',
                pid: 'jobs',
                index: '/jobs',
                title: '机会列表',
                permiss: 'career:jobs',
            },
        ],
    },
    {
        id: 'cocreation',
        icon: 'Connection',
        index: 'cocreation',
        title: '在地共创',
        children: [
            {
                id: 'cocreation:list',
                pid: 'cocreation',
                index: '/cocreation',
                title: '共创项目',
                permiss: 'career:cocreation',
            },
        ],
    },
    {
        id: 'assets',
        icon: 'Files',
        index: 'assets',
        title: '资源管理',
        children: [
            {
                id: 'assets:resources',
                pid: 'assets',
                index: '/resources',
                title: '资源列表',
                permiss: 'assets:resources',
            },
        ],
    },
    {
        id: '6',
        icon: 'DocumentAdd',
        index: '6',
        title: '附加页面',
        children: [
            {
                id: '61',
                pid: '6',
                index: '/ucenter',
                title: '个人中心',
                permiss: 'menu:extra:profile',
            },
            {
                id: '62',
                pid: '6',
                index: '/login',
                title: '登录',
                permiss: 'menu:extra:login',
            },
            {
                id: '63',
                pid: '6',
                index: '/register',
                title: '注册',
                permiss: 'menu:extra:register',
            },
            {
                id: '64',
                pid: '6',
                index: '/reset-pwd',
                title: '重设密码',
                permiss: 'menu:extra:reset',
            },
            {
                id: '65',
                pid: '6',
                index: '/403',
                title: '403',
                permiss: 'menu:extra:403',
            },
            {
                id: '66',
                pid: '6',
                index: '/404',
                title: '404',
                permiss: 'menu:extra:404',
            },
        ],
    },
];
